services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-7235}
      POSTGRES_DB: ${DB_NAME:-ai_assistant}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
